apiVersion: v1
kind: ConfigMap
metadata:
  name: django-config
  labels:
    app: django
data:
  SECRET_KEY: "django-insecure-0if40nf4nf93n4"
  DATABASE_URL: "postgres://postgres:EKAkItgy9c@my-postgresql:5432/postgres"
  ALLOWED_HOSTS: "*"
  DEBUG: "True"
